import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-evenly",
    backgroundColor: "#dfe4ea",
  },
  cartApp: {
    fontSize: 35,
    alignSelf: "flex-start",
    marginVertical: 10,
    fontWeight: 700,
    color: "#786DAE",
    shadowColor: "#000",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.8,
    shadowRadius: 0.5,
    elevation: 1,
    margin: 20,
  },
  total: {
    fontSize: 35,
    color: "#35374B",
    fontWeight: 300,
    margin: 35,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 1,
    shadowOpacity: 0.2,
  },
  foodListContainer: {
    position: "relative",
    flex: 1,
    width: 380,
    backgroundColor: "white",
    paddingVertical: 10,
    paddingHorizontal: 35,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    margin: 20,
  },
  titleList: {
    fontSize: 21,
    fontWeight: 500,
    marginVertical: 20,
    color: "lightgray",
  },
  foodItemContainer: {
    width: "100%",
    padding: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    color: "#35374B",
    borderBottomColor: "lightgray",
    borderBottomWidth: 1,
    fontSize: 20,
  },
  deleteButton: {
    padding: 10,
  },
  emptyText: {
    fontSize: 18,
    color: "gray",
    textAlign: "center",
    margin: 30,
  },
  iconButton: {
    padding: 10,
    borderRadius: 20,
    width: 60,
    height: 60,
    backgroundColor: "#968ec0",
    justifyContent: "center",
    alignItems: "center",
    margin: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "85%",
  },
  modalText: {
    fontSize: 18,
    color: "#35374B",
    textAlign: "center",
  },
  buttonContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    margin: 10,
  },
  camera: {
    flex: 1,
  },
  cameraIcons: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    marginBottom: 60,
  },
  pictureButton: {
    padding: 10,
    borderRadius: 30,
    width: 60,
    height: 60,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  previewImage: {
    width: 250,
    height: 250,
    margin: 20,
  },
});